name: cavs-environments
dependencies:
  - python=3.7
  - pandas
  - jupyter
  - numpy
  - rtree
  - scipy
  - matplotlib
  - tensorflow
  - nb_conda_kernels
  - pip:
      - pygame
      - pymunk=5.7.0
      - gym
      - ray[rllib]=1.0.0
      - ray[debug]
      - requests
      - setproctitle
      - lz4
      - image
      - stable_baselines
      - --editable=git+https://github.com/openai/spinningup.git#egg=spinup